# Generated by Django 5.0.7 on 2024-09-15 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a3_paper', models.PositiveIntegerField(default=0)),
                ('a4_paper', models.PositiveIntegerField(default=0)),
                ('white_ink', models.PositiveIntegerField(default=0)),
                ('black_ink', models.PositiveIntegerField(default=0)),
                ('cyan_ink', models.PositiveIntegerField(default=0)),
                ('magenda_ink', models.PositiveIntegerField(default=0)),
                ('yellow_ink', models.PositiveIntegerField(default=0)),
                ('total_due_vendors', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('waste', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('investment', models.FloatField(default=0)),
                ('total_profit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Other_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('GSM', models.IntegerField()),
                ('buying_price', models.FloatField()),
                ('available', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('front_print', models.CharField(blank=True, max_length=10, null=True)),
                ('front_design', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('back_print', models.CharField(blank=True, max_length=10, null=True)),
                ('back_design', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('mockup_front', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('mockup_back', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('advance_amount', models.FloatField(default=0)),
                ('advance_paid', models.BooleanField(default=False)),
                ('order_confirmed', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('collection_amount', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('vendor_profit', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('customer_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer_full_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('manager', 'Manager'), ('operator', 'Operator')], default='vendor', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_applied', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('page_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('nid', models.FileField(blank=True, null=True, upload_to='upload')),
                ('profit', models.FloatField(default=0)),
                ('due', models.FloatField(default=0)),
                ('mobile_banking', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_banking_number', models.IntegerField(blank=True, null=True)),
                ('total_profit', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
